name: ☁️ Hava CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Kodu yüklə (Checkout)
        uses: actions/checkout@v4

      - name: ☕ JDK 17 quraşdır
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 🚀 Testləri işə sal
        run: sh ./gradlew test